# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(blank=True, max_length=500)),
                ('college', models.TextField(blank=True, max_length=500)),
                ('mobile', models.IntegerField(blank=True)),
                ('city', models.TextField(blank=True, max_length=1000)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=128)),
                ('elanids', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
