# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='collge',
            new_name='college',
        ),
    ]
