# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20171226_2142'),
        ('Auth', '0004_auto_20171226_2136'),
    ]

    operations = [
    ]
