# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_merge_20171227_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
