# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_auto_20171208_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
