# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20171215_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
