# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_auto_20171217_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='elan_id',
            new_name='elanid',
        ),
    ]
