# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_auto_20171217_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='elanids',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
