# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 06:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0013_auto_20171217_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elanids',
            field=models.CharField(default=1, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
            preserve_default=False,
        ),
    ]
