# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0014_profile_elanids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='elanids',
            field=models.IntegerField(max_length=4),
        ),
    ]
