# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171221_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventname',
            name='eventid',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
