# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_eventregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='event',
            field=models.CharField(max_length=1000),
        ),
    ]
