# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20171104_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.EventName'),
        ),
    ]
