# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20171104_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregister',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregister',
            name='user',
        ),
    ]
